### ISSUE TITLE
Замечания по экзамену 7-9

### ISSUE THREAD

**Issue by AndriiLitvin** [didyk/didyk.github.io#10]
судя по вчерашниму вебинару то там такие экраны
320-479 480-767 768-959 и 960

и вынеси медиа квери в отдельный файл
не хватает экрана 320

http://joxi.ru/12MjzPDS4qY9nA
-
1)стиль текста по всему макету не тот
2) это не радиобатоны анавигация слайдера
3)4) нет стрелок слайдера
5)стиль
6) отступ больше
7)не радиобатоны а навигация

**Comment by didyk** [comment]
Все хватает, прописано же - с 960-769, 768-480, 481-320

**Comment by didyk** [comment]
И как это стиль текста другой, если это легуаготик

**Comment by didyk** [comment]
И с 319 тоже есть макет

**Comment by didyk** [comment]
И как вынести и зачем медиа квейрис?

**Comment by didyk** [comment]
И в 6 отступ не больше. По пиксельной точности все ок, просто там текста меньше, а у меня больше

**Comment by didyk** [comment]
переделал

**Comment by AndriiLitvin** [comment]
Вынести все медиаквери в один файл. и там 4 макета 320 480 768 и 960
320-479(макет 320) 480-767(макет 480) 768-959(макет 768) и 960(макет 960, тут max-width:960px; на всех экранах которые больше)

вот такое на хроме http://joxi.ru/eAO1zP7i4wBR6m
проверяю на мозиле выходит как то так http://joxi.ru/l2Z64PNu8DoQQ2(960)

1. экран 960 http://joxi.ru/l2Z64PNu8DoQQ2
-
0н отображается тут как 768 и как то криво
1)тут все в один ряд должно быть
2)подзаголовок полез
3)полез
4)6)тоже сместилось
5)тут паддинги у блока другие и текст режится
7)поход у тебя вместо 960 подгребся стиль макета 768
+ стрелочки вообще не видно.

2. Экран 768 http://joxi.ru/a2XQzB3Hy06XNA
-
он поход подтягивает макет 480
хех а 480 подгребает 320 макет

пересмотри пожалуйста все. и если что отпиши в скайп.

**Comment by didyk** [comment]
+++++++ все переделал

**Comment by didyk** [comment]
проверяй быстрее, там по-любом еще баги есть)

**Comment by didyk** [comment]
Андрей, куда пропал?

**Comment by AndriiLitvin** [comment]
> проверяй быстрее, там по-любом еще баги есть)

если знал что есть баги почему не правил? ты же знаешь что я зачет не поставлю.
или ты просто из за принципа так делаешь? я конечно должен проверять но я на каждые комменты теряю время а мимо вас есть еще задачи которые нужно сдать в срок.

**Comment by AndriiLitvin** [comment]
воот http://joxi.ru/1A5pK7zFKKZ882 при большом экране делается вот такое
проверяю на мозиле.
Чтоб я засчитал экзамен должна быть сделана 9 работа

Экран 960 http://joxi.ru/l2Z64PNu88aPO2
-
1) нужен отступ. стрелки нет. как на пункте 2)
3) навигация не та. там цвет другой
4)нет триугольника
5) навигация поехала
6) их лучше делать через обычные картинки так как если один поменяется прийдется коцать весь спрайт

Экран 768 http://joxi.ru/Dr8ERJ6Fkkp7Dm
-
1) менюшка не та
2)полезло
3)в одну строчку
+ там что то вообще на макет не очень похожее

Экран 480 http://joxi.ru/n2Y5gPkSjjRgM2
-
1) сделать просто надпись
2) стрелка залезла
3)нет активного элемента
4)поехало
5)полезло
6)отцентрировать

Экран 320 http://joxi.ru/brR6zPluQQ4gDr
1)Выровнять
2)сделать надпись и отцентровать
3)ширина меньше
4) переместить навигацию 
5)6) все сьехало

**Comment by didyk** [comment]
Все переделал под ту прогу

**Comment by didyk** [comment]
давай уже зачет)

**Comment by AndriiLitvin** [comment]
я б с радостью) ну тут..

Экран 320
-
 http://joxi.ru/nAy8vNqFXX6BW2
1)отцентрируй. убери флоат убери по бокам паддинги сделай margin:0 auto; text-align:center;
2)убрать отступ и отцентрировать

3)http://joxi.ru/krDDzYOu007VDr - отступ и выровнять
4)http://joxi.ru/L21b6x0F661oBA - текст обрезало и высоту блока подогнать
5)http://joxi.ru/5mdMgP7ivv7oK2 - отступ больше 

Экран 480 
-
1)http://joxi.ru/ZrJyzPXs11dPaA - там в одну строчку. там шрифт меньше. пересмотри размеры шрифтов на всех макетах
2)http://joxi.ru/5mdMgP7ivv7zD2 - меньше шрифт. и уже блок
3)http://joxi.ru/RmzkEJqFWWgPK2 - ширина блока мешьше  + паддинги в блоке 
4)http://joxi.ru/823pdlkF6671nA- отступы наоборот вверху меньше внизу больше
5)http://joxi.ru/Y2L0zPXsnn4Bv2 - ширина меньше
6)http://joxi.ru/a2XQzB3Hyyv6LA там ховера нет  а если даже есть то не такой жесткий

**Comment by didyk** [comment]
переделал все под пиксель перфектом и под приложения

**Comment by AndriiLitvin** [comment]
был бы ЗАЧЕТ. но блин. у тебя с html5 только header , а в задании Нужно использовать html5-теги
https://github.com/goit-fe/markup_fe2o/tree/master/lesson_07-8

давай поменяй теги и будет зачет)

**Comment by didyk** [comment]
поменял теги)

**Comment by AndriiLitvin** [comment]
там еще section можно было добавить)) ЗАЧЕТ
