### ISSUE TITLE
Замечания по работе 5.1 cadastre

### ISSUE THREAD

**Issue by AndriiLitvin** [didyk/didyk.github.io#7]
http://joxi.ru/Vm67Z8QsBzGa2Z
1)при широком екране меню улетает
2)Кнопка не картинкой. сверстай ее
3)убери повторение и сделай бекграунд сайз ковер
5) под кнопкой фейсбука тоже не картинкой а сверстать
6) в инпутах надпись через плейсхолдер

**Comment by didyk** [comment]
Плейсхолдер мы только в 6 начали использовать)

**Comment by AndriiLitvin** [comment]
ну а гугл зачем? то что вам дают на лекциях это малая часть, нужно учится правильно гуглить) Гугл все знает))

**Comment by didyk** [comment]
исправил

**Comment by AndriiLitvin** [comment]
>а меню при широком экране полюбом улетает, там же флоат райт

сделай чтоб не улетато. пихаешь контент в контейнер задаешь ему ширину 1215px и центрируешь этот контейнер

**Comment by didyk** [comment]
Через абсолюты они у меня улетали, По-этому сделал так

**Comment by didyk** [comment]
переделал 5

**Comment by AndriiLitvin** [comment]
ЗАЧЕТ
